name: deepcfr

advantage_net:
  hidden_sizes: [256, 256]
  dropout: 0.0
strategy_net:
  hidden_sizes: [256, 256]
  dropout: 0.0

advantage_buffer_size: 1_000_000
strategy_buffer_size: 4_000_000

traversals_per_iteration: 20_000
advantage_train_steps: 4_000
strategy_train_steps: 4_000
batch_size: 1024

learning_rate: 3.0e-4
grad_clip: 5.0
